# 公共配置文件
spring:
  application:
    name: api-backend
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
  # 默认 dev 环境
  #  profiles:
  #    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/#
    username: #
    password: #
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: #
    password: #
    virtualHost: /
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        # 确定机制
        acknowledge-mode: manual
  # application.properties
  task:
    scheduling:
      pool:
        size: 5


server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        #cookie作用域
#        domain: #
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认为 0）


dubbo:
  application:
    name: dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
